### ISSUE TITLE
Friendly request to change the name of this project?

### ISSUE THREAD

**Issue by Hansaplast** [mohamedawnallah/ConnectMeHub#1]
I sincerely apologize to have to ask this question ... (I have tried to find your contact info, but wasn't able to)

As much as I appreciate open source projects like yours; 
The name you picked for your project is 100% identical (capitals included) to one of my [macOS applications](https://www.tweaking4all.com/os-tips-and-tricks/macosx-tips-and-tricks/connect-network-shares-mac/) which been around for 8+ years now.
 
I'm sure this wasn't done intentionally, but it has confused at least one of my users.
So my friendly request to change the name of your project to avoid confusion 😊

**Comment by moawnallah** [comment]
Sorry for the inconvenience, @Hansaplast! And thanks for letting me know. I just renamed the project to `ConnectMeHub` :)

**Comment by Hansaplast** [comment]
No problem 😊 -- thank you for taking the effort to change the name. ConnectMeHub sounds good too 😉
